name: pdd
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.5
  flutter_native_splash: ^2.2.9
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  dio: ^4.0.6

  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  overlay_support: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    # - assets/pdd/images/A_B/
    # - assets/pdd/images/C_D/
    - assets/pdd/questions/A_B/tickets/
    # - assets/pdd/questions/A_B/topics/
    # - assets/pdd/questions/C_D/tickets/
    # - assets/pdd/questions/C_D/topics/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
